services:
  redis:
    restart: unless-stopped
    image: redis:7.4.1
    ports:
      - "6379:6379"
    env_file: .env
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - redis-data:/data

  worker:
    build: .
    container_name: worker
    restart: always
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app # Mount your code (live)
      - node_modules:/app/node_modules # Persist node_modules

volumes:
  redis-data:
  node_modules:
